/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateProyectArgs } from "./CreateProyectArgs";
import { UpdateProyectArgs } from "./UpdateProyectArgs";
import { DeleteProyectArgs } from "./DeleteProyectArgs";
import { ProyectFindManyArgs } from "./ProyectFindManyArgs";
import { ProyectFindUniqueArgs } from "./ProyectFindUniqueArgs";
import { Proyect } from "./Proyect";
import { User } from "../../user/base/User";
import { ProyectService } from "../proyect.service";

@graphql.Resolver(() => Proyect)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ProyectResolverBase {
  constructor(
    protected readonly service: ProyectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "read",
    possession: "any",
  })
  async _proyectsMeta(
    @graphql.Args() args: ProyectFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Proyect])
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "read",
    possession: "any",
  })
  async proyects(
    @graphql.Args() args: ProyectFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proyect[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Proyect",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Proyect, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "read",
    possession: "own",
  })
  async proyect(
    @graphql.Args() args: ProyectFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proyect | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Proyect",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Proyect)
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "create",
    possession: "any",
  })
  async createProyect(
    @graphql.Args() args: CreateProyectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proyect> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Proyect",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Proyect"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => Proyect)
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "update",
    possession: "any",
  })
  async updateProyect(
    @graphql.Args() args: UpdateProyectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proyect | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Proyect",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Proyect"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Proyect)
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "delete",
    possession: "any",
  })
  async deleteProyect(
    @graphql.Args() args: DeleteProyectArgs
  ): Promise<Proyect | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Proyect",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: Proyect,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
